// email obfuscator and stuff
window.onload = function() {
  var email, i, item, len, numberletters, obfuscated;
  $.ajax({
    url: 'https://api.github.com/users/soops',
    type: 'GET',
    dataType: 'JSONP',
    success: function(userdata) {
      $('#profile').css('background-image', 'url(' + userdata.data['avatar_url'] + ')');
    },
    error: function(e) {
      if (typeof console !== "undefined" && console !== null) {
        console.error(e);
      }
    }
  });

  obfuscated = [5, 20, 8, 1, 14, 1, 18, 20, 5, 18, 2, 5, 18, 18, 25, "@", 7, 13, 1, 9, 12, ".", 3, 15, 13];
  numberletters = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"];
  email = [];
  for (i = 0, len = obfuscated.length; i < len; i++) {
    item = obfuscated[i];
    if (!isNaN(item)) {
      email.push(numberletters[item - 1]);
    } else {
      email.push(item);
    }
    if (typeof console !== "undefined" && console !== null) {
      console.log(item);
    }
  }
  $("#email").attr("href", "mailto:" + (email.join("")));

  $.getJSON("http://ws.audioscrobbler.com/2.0/?method=user.getRecentTracks&user=soodologica&api_key=67bc224ceb7cea73cf835a56d247d15a&limit=2&format=json&callback=?", function(data) {
      var html = '';
      var counter = 1;
      $.each(data.recenttracks.track, function(i, item) {
          if(counter == 1) {
              html += item.name + ' by ' + item.artist['#text'];
          }
          counter++
      });
      $('#coolcool').html(html + ".");
  });
};

// ---
// generated by coffee-script 1.9.2
