window.onload = function() {
  return $.ajax({
    url: "https://api.github.com/users/sargeant45",
    type: "GET",
    dataType: "JSONP",
    success: function(userdata) {
      document.getElementById("repos").innerHTML = userdata.data["public_repos"];
      document.getElementById("gists").innerHTML = userdata.data["public_gists"];
      $("#profile").css("background-image", "url(" + userdata.data['avatar_url'] + ")");
    },
    error: function(e) {
      console.log(e);
    }
  });
};

// ---
// generated by coffee-script 1.9.2
